# -*- coding: utf-8 -*-
"""derivadas simbolicas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EHnG1OsgG3Sx1zr-EYqhRcT7oAyXEUT
"""

#### 3. **Código das Derivadas Simbólicas**

import sympy as sp

# Define os símbolos x e y
x, y = sp.symbols('x y')

# Define a expressão simbólica y = x^3
y = x**3

# Calcula a derivada simbólica
g = sp.diff(y, x)

# Exibe a expressão e a derivada
print(f"Expressão: {y}")
print(f"Derivada: {g}")

# Plota a função e sua derivada
sp.plot(y, g, title="Função e Derivada Simbólica", legend=True, show=True)