# -*- coding: utf-8 -*-
"""Massa mola Euler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Di4OgZtVJZ_T2BHkDz7ytD1XG8ATRVAo

# **Euler-Explícito**
"""

import numpy as np
import matplotlib.pyplot as plt

x0 = 2
v0 = 1
w0_squared = 3
h= 0.01
steps = 1000

def derivadas(x,v):
  dxdt = v
  dvdt = -w0_squared * x
  return dxdt, dvdt

def euler_explicito(x0, v0, h, steps):
  x = x0
  v = v0
  t = 0
  posicoes = [x]
  tempos = [t]
  velocidades = [v]
  for _ in range(steps):
    dxdt, dvdt = derivadas(x,v)
    x += dxdt * h
    v += dvdt * h
    t += h
    posicoes.append(x)
    velocidades.append(v)
    tempos.append(t)

  return posicoes,velocidades, tempos

posicoes,velocidades, tempos = euler_explicito(x0,v0, h, steps)

plt.plot(tempos, posicoes, label="Posição")
plt.plot(tempos, velocidades, label="Velocidade",linestyle="--")
plt.xlabel("Tempo")
plt.ylabel("Posição / Velocidade")
plt.title("Sistema Massa-Mola - Método de Euler Explicito")
plt.grid(True)
plt.show()

plt.plot(posicoes,velocidades, label="Velocidade")
plt.xlabel("Posição")
plt.ylabel("Velocidade")
plt.title("Sistema Massa-Mola - Método de Euler Explicito")
plt.grid(True)
plt.show()